version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app
    env_file:
      - ./Backend/.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - nexus-network

  frontend:
    build:
      context: ./Frontend/chat-interface
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend/chat-interface:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api/v1
    depends_on:
      - backend
    networks:
      - nexus-network

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    env_file:
      - ./Backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nexus"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - nexus-network

networks:
  nexus-network:
    driver: bridge

volumes:
  postgres_data:
